### PR TITLE
Add desktop launcher to open $XDG_DATA_HOME for mods

### PR DESCRIPTION
**Pull request by fpiesche**
cc @lavenderdotpet - this will add a second app launcher shortcut to open the LQ Flatpak mod directory! One thing I'm not sure about is how to handle the icon here... I was thinking about maybe adding like a hammer+wrench or gear badge to it but I'm very not certain how to best approach this :thinking:

### CODE REVIEW

**Comment by lavenderdotpet** [comment]
I was thinking the the main app would be the launcher and that there wouldn't be a 2nd app

**Comment by lavenderdotpet** [comment]
oh does all this do is open the mod folder 
I'll mock something up

**Comment by pnahratow** [comment]
Flathub staff told us in the initial submission that the metadata files like (desktop, meta.xml, icon) should go in the original repository. I think this is maybe an additional type of verification. I don't know I find it kind of annoying tbh since the files are much better suited here.

We have however did what they said and the files are here https://github.com/lavenderdotpet/LibreQuake/tree/main/docs/flatpak-metadata

**Comment by fpiesche** [comment]
It's less a matter of verification as to make sure that the metadata being shown on Flathub is up to date and maintained, given that they have a lot of submissions that come from outside of the projects they're building. In either case I'll close this for now as we've discussed an alternative way of handling this...

**Pull request closed without merging**
